---
stages:
  - build

build:
  stage: build
  # only:
  #   - /^\d+\.\d+\.\d+(-[-0-9A-Za-z_.]+)?/
  # except:
  #   - branches
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(-[-0-9A-Za-z_.]+)?$/'
  script:
    - docker build . --build-arg="NGINX_VERSION=${CI_COMMIT_TAG%%-*}" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
